# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: |
            pip install tox
          name: Install tox
      - run:
          command: |
            tox
          name: Run tests
  dependency-check:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: |
            pip install safety
          name: Install safety
      - run:
          command: |
            safety check -r requirements.txt --full-report
          name: Check dependencies

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  primary: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - test
      - dependency-check
